spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://1authority-interns.1rivet.com:5004
          jwkSeturi: https://1authority-interns.1rivet.com:5004/.well-known/openid-configuration/jwks
          audiences: DeskBookApi
  datasource:
    url: jdbc:sqlserver://172.16.1.230;databaseName=DeskBookQA;encrypt=true;trustServerCertificate=true
    username: deskbookqa
    password: deskbookqa@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

server:
   port: 9446
   ssl: 
     enabled: true
     key-store-type: PKCS12
     key-store: file:C:\\deskbook-qa-userapi\\qa-deskbook-userapi.1rivet.com.p12
     key-store-password: admin
     key-alias: qa-deskbook-userapi.1rivet.com
       


          
          
